services:
  datadog-agent:
    image: gcr.io/datadoghq/agent:7
    environment:
      DD_API_KEY: ${DD_API_KEY:?Defina DD_API_KEY no .env}
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_APM_ENABLED: "true"
      DD_APM_NON_LOCAL_TRAFFIC: "true"
      DD_LOGS_ENABLED: "true"
      DD_PROCESS_AGENT_ENABLED: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "8126:8126"

  retail-processor:
    build: .
    command: ["./scripts/run_processor.sh"]
    environment:
      DD_AGENT_HOST: datadog-agent
      DD_SERVICE: retail-processor
      DD_LLMOBS_ML_APP: retail-assistant
      DD_LLMOBS_ENABLED: "1"
      DD_ENV: ${DD_ENV:-dev}
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_LLMOBS_AGENTLESS_ENABLED: ${DD_LLMOBS_AGENTLESS_ENABLED:-true}
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      USE_MOCK_LLM: ${USE_MOCK_LLM:-auto}
    ports:
      - "8002:8002"
    depends_on:
      - datadog-agent

  retail-gateway:
    build: .
    command: ["./scripts/run_gateway.sh"]
    environment:
      DD_AGENT_HOST: datadog-agent
      DD_SERVICE: retail-gateway
      DD_LLMOBS_ML_APP: retail-assistant
      DD_LLMOBS_ENABLED: "1"
      DD_ENV: ${DD_ENV:-dev}
      DD_API_KEY: ${DD_API_KEY}
      DD_SITE: ${DD_SITE:-datadoghq.com}
      DD_LLMOBS_AGENTLESS_ENABLED: ${DD_LLMOBS_AGENTLESS_ENABLED:-true}
      PROCESSOR_URL: http://retail-processor:8002
      OPENAI_API_KEY: ${OPENAI_API_KEY:-}
      USE_MOCK_LLM: ${USE_MOCK_LLM:-auto}
    ports:
      - "8001:8001"
    depends_on:
      - retail-processor
      - datadog-agent
